// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package server;

public final class JobImpl_Stub
    extends java.rmi.server.RemoteStub
    implements interfaces.Job, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getResult_0;
    private static java.lang.reflect.Method $method_isDone_1;
    
    static {
	try {
	    $method_getResult_0 = interfaces.Job.class.getMethod("getResult", new java.lang.Class[] {});
	    $method_isDone_1 = interfaces.Job.class.getMethod("isDone", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public JobImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getResult()
    public java.lang.Object getResult()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getResult_0, null, -4913581871456071705L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of isDone()
    public boolean isDone()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_isDone_1, null, 4451682669232540140L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
