// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package client;

public final class Callback_Stub
    extends java.rmi.server.RemoteStub
    implements interfaces.CallbackIF, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_finish_0;
    private static java.lang.reflect.Method $method_getState_1;
    
    static {
	try {
	    $method_finish_0 = interfaces.CallbackIF.class.getMethod("finish", new java.lang.Class[] {int.class});
	    $method_getState_1 = interfaces.CallbackIF.class.getMethod("getState", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Callback_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of finish(int)
    public void finish(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_finish_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 9033525737839772808L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getState(String)
    public void getState(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_getState_1, new java.lang.Object[] {$param_String_1}, -2926133103654354304L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
