// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package client;

public final class Client_Stub
    extends java.rmi.server.RemoteStub
    implements java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    // constructors
    public Client_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
}
